package co.edu.uniquindio.proyecto.modelo;

public enum Alergia {
    ALERGIA_AL_POLEN,
    ALERGIA_AL_POLVO,
    ALERGIA_ALIMENTARIA,
    ALERGIA_AL_LÁTEX,
    ALERGIA_A_LOS_ÁCAROS,
    ALERGIA_AL_SOL,
    ALERGIA_A_LOS_GATOS,
    ALERGIA_A_LOS_PERROS,
    ALERGIA_AL_MARISCO,
    ALERGIA_AL_CACAHUETE,
    ALERGIA_A_LOS_FRUTOS_SECOS,
    ALERGIA_A_LAS_AVISPAS,
    ALERGIA_AL_POLLO,
    ALERGIA_AL_HUEVO,
    ALERGIA_A_LOS_MEDICAMENTOS,
    ALERGIA_A_LA_SOJA,
    ALERGIA_AL_TOMATE,
    ALERGIA_AL_PESCADO,
    ALERGIA_AL_TRIGO,
    ALERGIA_AL_MANÍ
}
